<?php
/**
 * Created by JetBrains PhpStorm.
 * User: anamika
 * Date: 20/5/15
 * Time: 3:22 PM
 * To change this template use File | Settings | File Templates.
 */

/**
 * implements hook_menu()
 */
function person_menu(){
    $items  = array();
    $items['person'] = array(
        'title' => "Person",
        'page callback' => "person_personal_info", // after visit drupal6/person, person_personal_info() function is called
        'access callback' => true,	// must return true, otherwise it will not visible as menu item
        'type' => MENU_NORMAL_ITEM, // drupal's default menu type
        'weight' => '10', // we want to display person link below in our nav menu
    );
    return $items; // finally, do not forget to return $items array
}


/**
 * callback function for person
 *
 */
function person_personal_info(){
    $output = 'Name: Anamika Verma </br>';
    $output .= 'City: Pune </br>';
    $output .= 'Country: India </br>';
    return $output;
}